---
name: CI

on:
    push:
        branches:
            - trunk
        paths-ignore:
            - .editorconfig
            - .gitignore
            - CONTRIBUTING.md
            - LICENSE-3rdparty.csv
            - LICENSE.md
            - NOTICE
            - README.md
            - SUPPORT.md
    pull_request:
        branches:
            - trunk
        paths-ignore:
            - .editorconfig
            - .gitignore
            - CONTRIBUTING.md
            - LICENSE-3rdparty.csv
            - LICENSE.md
            - NOTICE
            - README.md
            - SUPPORT.md

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

            - name: Setup node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: 22
                  registry-url: https://npm.pkg.github.com/

            - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              id: yarn-cache
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-node22-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-node22-yarn-

            - name: Build Typescript
              run: yarn && yarn build

    test:
        name: Test
        needs: [build]
        runs-on: 'ubuntu-latest'

        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

            - name: Setup node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: 22
                  registry-url: https://npm.pkg.github.com/

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn

            - name: Test
              run: yarn && yarn test
